const canvas = document.querySelector('#canvasElem');
const coords = canvas.getBoundingClientRect();
const offsets = {
    x: coords.left,
    y: coords.top
};
canvas.onmousemove = e => {
    const ctx = canvas.getContext('2d');
    ctx.lineTo(e.clientX - offsets.x, e.clientY - offsets.y);
    ctx.stroke();
};
async function submit() {
    const blob = await new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
    const response = await fetch('./post-this-message', {
        method: 'POST',
        body: blob
    });
    // Here we also didn’t need to set Content-Type manually, because a Blob object has a built-in type
    // ( here 'image/png', as generated by toBlob )
    alert(`server response: ${await response.text()}`);
}